Spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/pbl
    username: sa
    password:
    driver-class-name: org.h2.Driver # ?? JPA ?? ???? ?

  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    show_sql: true

    hibernate:
      ddl-auto: create
    # ?????? ????? ?? ?? ??? ?? ??? ???(drop) ?? ??

    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

    open-in-view: false

